# 🧩 Request Issue Assignment

✅ **Please read the following before submitting**:
- You can only be assigned one issue at a time.
- PR for unassigned issues will be **rejected**.
- You must get your current PR **approved** before claiming a new issue.

---

**💬 Your Discord Username (Optional)**  
e.g. johndoe123

**📌 Issue Level**
- [ ] Level 1 (Beginner – 2-3 days)
- [ ] Level 2 (Intermediate – 4-6 days)
- [ ] Level 3 (Advanced – 7-10 days)

**🔥 Why do you want to work on this?**  
[Write here]

---

🕐 **You are expected to complete the issue in the specified time. If inactive for 3 days, it may be unassigned.**  
📩 Need more time? Please inform the maintainer *before* it’s marked stale.
