name: Issue Greetings

on:
  issues:
    types: [opened, assigned]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add greeting comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              ...context.issue,
              body: `🎉 Thank you @${context.payload.assignee?.login || context.payload.issue.user.login} for picking up this issue!  
            Please make sure to follow our contributing guidelines here 👉 [Contributing Guidelines](https://github.com/DevSyncx/DevSync/blob/main/CONTRIBUTING.md)
            Don't forget to give this repo a 🌟
            Happy coding !!`
            })
